<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'category_slug' => 'mobiles',
                'title' => 'iPhone 15',
                'slug' => 'iphone-15',
                'description' => 'A16 Bionic chip, Dynamic Island.',
                'price' => 74999,
                'discount_percent' => 10,
                'rating' => 4,
                'stock' => 35,
                'image_url' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80&iphone',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'mobiles',
                'title' => 'Samsung S24',
                'slug' => 'samsung-s24',
                'description' => 'Galaxy AI and AMOLED display.',
                'price' => 69999,
                'discount_percent' => 12,
                'rating' => 5,
                'stock' => 69,
                'image_url' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80&samsung',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'mobiles',
                'title' => 'Google Pixel 8 Pro',
                'slug' => 'google-pixel-8-pro',
                'description' => 'Google AI and best camera.',
                'price' => 106999,
                'discount_percent' => 15,
                'rating' => 5,
                'stock' => 42,
                'image_url' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80&pixel',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'mobiles',
                'title' => 'Samsung Z Flip 5',
                'slug' => 'samsung-z-flip-5',
                'description' => 'Foldable innovation.',
                'price' => 99999,
                'discount_percent' => 10,
                'rating' => 5,
                'stock' => 40,
                'image_url' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80&flip-phone',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'mobiles',
                'title' => 'OnePlus 12',
                'slug' => 'oneplus-12',
                'description' => 'Smooth performance, Hasselblad camera.',
                'price' => 64999,
                'discount_percent' => 8,
                'rating' => 4,
                'stock' => 73,
                'image_url' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80&oneplus',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'mobiles',
                'title' => 'Nothing Phone (2)',
                'slug' => 'nothing-phone-2',
                'description' => 'Unique glyph interface.',
                'price' => 44999,
                'discount_percent' => 5,
                'rating' => 4,
                'stock' => 59,
                'image_url' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80&nothing-phone',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'mobiles',
                'title' => 'Google Pixel 7a',
                'slug' => 'google-pixel-7a',
                'description' => 'Compact and powerful.',
                'price' => 39999,
                'discount_percent' => 20,
                'rating' => 4,
                'stock' => 42,
                'image_url' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80&pixel-7',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'mobiles',
                'title' => 'Moto Edge 50 Pro',
                'slug' => 'moto-edge-50-pro',
                'description' => 'Curve display, fast charging.',
                'price' => 31999,
                'discount_percent' => 15,
                'rating' => 4,
                'stock' => 24,
                'image_url' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80&motorola',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'mobiles',
                'title' => 'Realme GT 5',
                'slug' => 'realme-gt-5',
                'description' => 'Performance beast.',
                'price' => 38999,
                'discount_percent' => 10,
                'rating' => 4,
                'stock' => 12,
                'image_url' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80&realme',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'mobiles',
                'title' => 'Poco F6',
                'slug' => 'poco-f6',
                'description' => 'Gaming powerhouse.',
                'price' => 29999,
                'discount_percent' => 12,
                'rating' => 5,
                'stock' => 79,
                'image_url' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80&poco',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'mobiles',
                'title' => 'iPhone 14',
                'slug' => 'iphone-14',
                'description' => 'Classic Apple performance.',
                'price' => 59999,
                'discount_percent' => 15,
                'rating' => 4,
                'stock' => 19,
                'image_url' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80&iphone-14',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'mobiles',
                'title' => 'Samsung A55',
                'slug' => 'samsung-a55',
                'description' => 'Premium mid-range.',
                'price' => 39999,
                'discount_percent' => 10,
                'rating' => 4,
                'stock' => 93,
                'image_url' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80&samsung-a',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'mobiles',
                'title' => 'Vivo V30 Pro',
                'slug' => 'vivo-v30-pro',
                'description' => 'Aura light portrait camera.',
                'price' => 41999,
                'discount_percent' => 8,
                'rating' => 4,
                'stock' => 46,
                'image_url' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80&vivo',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'mobiles',
                'title' => 'Oppo Reno 11',
                'slug' => 'oppo-reno-11',
                'description' => 'Sleek design, great selfies.',
                'price' => 37999,
                'discount_percent' => 12,
                'rating' => 4,
                'stock' => 64,
                'image_url' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80&oppo',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'mobiles',
                'title' => 'Redmi Note 13',
                'slug' => 'redmi-note-13',
                'description' => 'Best value smartphone.',
                'price' => 17999,
                'discount_percent' => 25,
                'rating' => 4,
                'stock' => 33,
                'image_url' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80&redmi',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'mobiles',
                'title' => 'Samsung S23 FE',
                'slug' => 'samsung-s23-fe',
                'description' => 'Flagship features, fan edition.',
                'price' => 49999,
                'discount_percent' => 18,
                'rating' => 5,
                'stock' => 12,
                'image_url' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80&samsung-fe',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'mobiles',
                'title' => 'iPhone 13',
                'slug' => 'iphone-13',
                'description' => 'Compact and reliable.',
                'price' => 48999,
                'discount_percent' => 22,
                'rating' => 5,
                'stock' => 95,
                'image_url' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80&iphone-13',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'mobiles',
                'title' => 'OnePlus Nord CE 4',
                'slug' => 'oneplus-nord-ce-4',
                'description' => 'Core edition performance.',
                'price' => 24999,
                'discount_percent' => 10,
                'rating' => 4,
                'stock' => 6,
                'image_url' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80&oneplus-nord',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'mobiles',
                'title' => 'Moto G84',
                'slug' => 'moto-g84',
                'description' => 'Pantone colors, leather finish.',
                'price' => 18999,
                'discount_percent' => 15,
                'rating' => 4,
                'stock' => 10,
                'image_url' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80&moto-g',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'mobiles',
                'title' => 'Samsung M34',
                'slug' => 'samsung-m34',
                'description' => 'Massive battery, great display.',
                'price' => 15999,
                'discount_percent' => 20,
                'rating' => 4,
                'stock' => 67,
                'image_url' => 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=900&q=80&samsung-m',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'laptops',
                'title' => 'MacBook Air M3',
                'slug' => 'macbook-air-m3',
                'description' => 'Apple M3 chip, all-day battery.',
                'price' => 114900,
                'discount_percent' => 8,
                'rating' => 5,
                'stock' => 50,
                'image_url' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80&macbook',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'laptops',
                'title' => 'ASUS Vivobook 16',
                'slug' => 'asus-vivobook-16',
                'description' => 'Productivity powerhouse.',
                'price' => 55999,
                'discount_percent' => 18,
                'rating' => 4,
                'stock' => 88,
                'image_url' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80&laptop-asus',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'laptops',
                'title' => 'Dell XPS 15',
                'slug' => 'dell-xps-15',
                'description' => 'OLED display, creator choice.',
                'price' => 245000,
                'discount_percent' => 5,
                'rating' => 5,
                'stock' => 78,
                'image_url' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80&dell-xps',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'laptops',
                'title' => 'Lenovo Legion 5 Pro',
                'slug' => 'lenovo-legion-5-pro',
                'description' => 'RTX gaming performance.',
                'price' => 155000,
                'discount_percent' => 12,
                'rating' => 5,
                'stock' => 58,
                'image_url' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80&gaming-laptop',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'laptops',
                'title' => 'HP Spectre x360',
                'slug' => 'hp-spectre-x360',
                'description' => '2-in-1 luxury laptop.',
                'price' => 145000,
                'discount_percent' => 10,
                'rating' => 5,
                'stock' => 45,
                'image_url' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80&hp-spectre',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'laptops',
                'title' => 'Acer Swift Go',
                'slug' => 'acer-swift-go',
                'description' => 'OLED display, thin and light.',
                'price' => 62999,
                'discount_percent' => 20,
                'rating' => 4,
                'stock' => 41,
                'image_url' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80&acer-swift',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'laptops',
                'title' => 'Microsoft Surface Laptop 5',
                'slug' => 'microsoft-surface-laptop-5',
                'description' => 'Elegant design, touch screen.',
                'price' => 105000,
                'discount_percent' => 15,
                'rating' => 4,
                'stock' => 5,
                'image_url' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80&surface-laptop',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'laptops',
                'title' => 'Razer Blade 14',
                'slug' => 'razer-blade-14',
                'description' => 'Ultimate portable gaming.',
                'price' => 215000,
                'discount_percent' => 8,
                'rating' => 5,
                'stock' => 95,
                'image_url' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80&razer',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'laptops',
                'title' => 'MSI Stealth 16',
                'slug' => 'msi-stealth-16',
                'description' => 'Powerful yet slim gaming.',
                'price' => 189000,
                'discount_percent' => 10,
                'rating' => 5,
                'stock' => 80,
                'image_url' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80&msi-laptop',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'laptops',
                'title' => 'ASUS ROG Zephyrus G14',
                'slug' => 'asus-rog-zephyrus-g14',
                'description' => 'Best 14-inch gaming laptop.',
                'price' => 165000,
                'discount_percent' => 12,
                'rating' => 5,
                'stock' => 25,
                'image_url' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80&rog-zephyrus',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'laptops',
                'title' => 'HP Victus 15',
                'slug' => 'hp-victus-15',
                'description' => 'Entry-level gaming value.',
                'price' => 68999,
                'discount_percent' => 22,
                'rating' => 4,
                'stock' => 52,
                'image_url' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80&hp-victus',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'laptops',
                'title' => 'Lenovo Yoga 7i',
                'slug' => 'lenovo-yoga-7i',
                'description' => 'Versatile 2-in-1 experience.',
                'price' => 89999,
                'discount_percent' => 15,
                'rating' => 4,
                'stock' => 53,
                'image_url' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80&lenovo-yoga',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'laptops',
                'title' => 'Dell Inspiron 14',
                'slug' => 'dell-inspiron-14',
                'description' => 'Reliable work companion.',
                'price' => 52999,
                'discount_percent' => 18,
                'rating' => 4,
                'stock' => 65,
                'image_url' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80&dell-inspiron',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'laptops',
                'title' => 'Samsung Galaxy Book 3 Pro',
                'slug' => 'samsung-galaxy-book-3-pro',
                'description' => 'Ecosystem integration, AMOLED.',
                'price' => 135000,
                'discount_percent' => 10,
                'rating' => 5,
                'stock' => 83,
                'image_url' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80&galaxy-book',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'laptops',
                'title' => 'Acer Predator Helios 300',
                'slug' => 'acer-predator-helios-300',
                'description' => 'Classic gaming beast.',
                'price' => 115000,
                'discount_percent' => 20,
                'rating' => 5,
                'stock' => 80,
                'image_url' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80&predator',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'laptops',
                'title' => 'Apple MacBook Pro 14',
                'slug' => 'apple-macbook-pro-14',
                'description' => 'M3 Pro chip, Liquid Retina.',
                'price' => 199900,
                'discount_percent' => 5,
                'rating' => 5,
                'stock' => 40,
                'image_url' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80&macbook-pro',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'laptops',
                'title' => 'ASUS Zenbook 14',
                'slug' => 'asus-zenbook-14',
                'description' => 'Premium ultrabook.',
                'price' => 95000,
                'discount_percent' => 12,
                'rating' => 4,
                'stock' => 30,
                'image_url' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80&zenbook',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'laptops',
                'title' => 'HP Pavilion 15',
                'slug' => 'hp-pavilion-15',
                'description' => 'Modern multitasking.',
                'price' => 64000,
                'discount_percent' => 15,
                'rating' => 4,
                'stock' => 7,
                'image_url' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80&hp-pavilion',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'laptops',
                'title' => 'Lenovo IdeaPad Slim 3',
                'slug' => 'lenovo-ideapad-slim-3',
                'description' => 'Budget friendly performance.',
                'price' => 38000,
                'discount_percent' => 25,
                'rating' => 4,
                'stock' => 66,
                'image_url' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80&ideapad',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'laptops',
                'title' => 'Acer Aspire 5',
                'slug' => 'acer-aspire-5',
                'description' => 'Solid everyday usage.',
                'price' => 42000,
                'discount_percent' => 20,
                'rating' => 4,
                'stock' => 46,
                'image_url' => 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80&acer-aspire',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'fashion',
                'title' => 'Men Casual Shirt',
                'slug' => 'men-casual-shirt',
                'description' => 'Cotton comfort for daily wear.',
                'price' => 1199,
                'discount_percent' => 40,
                'rating' => 4,
                'stock' => 84,
                'image_url' => 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&q=80&shirt',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'fashion',
                'title' => 'Women Floral Midi Dress',
                'slug' => 'women-floral-midi-dress',
                'description' => 'Elegant summer style.',
                'price' => 2499,
                'discount_percent' => 30,
                'rating' => 5,
                'stock' => 100,
                'image_url' => 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&q=80&dress',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'fashion',
                'title' => 'Women High Heel Sandals',
                'slug' => 'women-high-heel-sandals',
                'description' => 'Formal and chic.',
                'price' => 3999,
                'discount_percent' => 50,
                'rating' => 4,
                'stock' => 92,
                'image_url' => 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&q=80&heels',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'fashion',
                'title' => 'Men Denim Jeans',
                'slug' => 'men-denim-jeans',
                'description' => 'Slim fit rugged denim.',
                'price' => 1999,
                'discount_percent' => 35,
                'rating' => 4,
                'stock' => 18,
                'image_url' => 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&q=80&jeans',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'fashion',
                'title' => 'Women Leather Handbag',
                'slug' => 'women-leather-handbag',
                'description' => 'Genuine leather, spacious.',
                'price' => 4500,
                'discount_percent' => 20,
                'rating' => 5,
                'stock' => 89,
                'image_url' => 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&q=80&handbag',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'fashion',
                'title' => 'Men Sports Sneakers',
                'slug' => 'men-sports-sneakers',
                'description' => 'Breathable workout shoes.',
                'price' => 2999,
                'discount_percent' => 45,
                'rating' => 4,
                'stock' => 49,
                'image_url' => 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&q=80&sneakers',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'fashion',
                'title' => 'Women Silk Saree',
                'slug' => 'women-silk-saree',
                'description' => 'Traditional ethnic wear.',
                'price' => 8500,
                'discount_percent' => 15,
                'rating' => 5,
                'stock' => 72,
                'image_url' => 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&q=80&saree',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'fashion',
                'title' => 'Men Leather Belt',
                'slug' => 'men-leather-belt',
                'description' => 'Classic brown leather.',
                'price' => 899,
                'discount_percent' => 50,
                'rating' => 4,
                'stock' => 23,
                'image_url' => 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&q=80&belt',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'fashion',
                'title' => 'Women Woolen Scarf',
                'slug' => 'women-woolen-scarf',
                'description' => 'Soft winter warmth.',
                'price' => 1299,
                'discount_percent' => 25,
                'rating' => 4,
                'stock' => 99,
                'image_url' => 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&q=80&scarf',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'fashion',
                'title' => 'Men Casual Hoodie',
                'slug' => 'men-casual-hoodie',
                'description' => 'Fleece lined comfort.',
                'price' => 1899,
                'discount_percent' => 30,
                'rating' => 4,
                'stock' => 94,
                'image_url' => 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&q=80&hoodie',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'fashion',
                'title' => 'Women Cotton T-shirt',
                'slug' => 'women-cotton-t-shirt',
                'description' => 'Everyday basics.',
                'price' => 799,
                'discount_percent' => 60,
                'rating' => 4,
                'stock' => 39,
                'image_url' => 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&q=80&tshirt',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'fashion',
                'title' => 'Men Formal Suit',
                'slug' => 'men-formal-suit',
                'description' => 'Sharp tailored business wear.',
                'price' => 12500,
                'discount_percent' => 10,
                'rating' => 5,
                'stock' => 80,
                'image_url' => 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&q=80&suit',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'fashion',
                'title' => 'Women Denim Jacket',
                'slug' => 'women-denim-jacket',
                'description' => 'Versatile layering piece.',
                'price' => 2200,
                'discount_percent' => 20,
                'rating' => 4,
                'stock' => 60,
                'image_url' => 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&q=80&denim-jacket',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'fashion',
                'title' => 'Men Cargo Pants',
                'slug' => 'men-cargo-pants',
                'description' => 'Multi-pocket functionality.',
                'price' => 1600,
                'discount_percent' => 25,
                'rating' => 4,
                'stock' => 29,
                'image_url' => 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&q=80&cargo-pants',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'fashion',
                'title' => 'Women Ankle Boots',
                'slug' => 'women-ankle-boots',
                'description' => 'Stylish suede finish.',
                'price' => 3400,
                'discount_percent' => 15,
                'rating' => 5,
                'stock' => 80,
                'image_url' => 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&q=80&boots',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'fashion',
                'title' => 'Men Polo T-shirt',
                'slug' => 'men-polo-t-shirt',
                'description' => 'Classic sporty look.',
                'price' => 999,
                'discount_percent' => 40,
                'rating' => 4,
                'stock' => 69,
                'image_url' => 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&q=80&polo',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'fashion',
                'title' => 'Women Yoga Leggings',
                'slug' => 'women-yoga-leggings',
                'description' => 'High stretch gym wear.',
                'price' => 1499,
                'discount_percent' => 30,
                'rating' => 4,
                'stock' => 31,
                'image_url' => 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&q=80&leggings',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'fashion',
                'title' => 'Men Bomber Jacket',
                'slug' => 'men-bomber-jacket',
                'description' => 'Urban street style.',
                'price' => 2800,
                'discount_percent' => 20,
                'rating' => 4,
                'stock' => 19,
                'image_url' => 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&q=80&bomber-jacket',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'fashion',
                'title' => 'Women Sunglasses',
                'slug' => 'women-sunglasses',
                'description' => 'Cat-eye frame protection.',
                'price' => 1800,
                'discount_percent' => 35,
                'rating' => 4,
                'stock' => 86,
                'image_url' => 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&q=80&sunglasses',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'fashion',
                'title' => 'Men Tracksuit',
                'slug' => 'men-tracksuit',
                'description' => 'Complete running set.',
                'price' => 3200,
                'discount_percent' => 25,
                'rating' => 4,
                'stock' => 79,
                'image_url' => 'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=900&q=80&tracksuit',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'electronics',
                'title' => 'Noise Cancelling Headphones',
                'slug' => 'noise-cancelling-headphones',
                'description' => 'Deep bass and ANC.',
                'price' => 8999,
                'discount_percent' => 22,
                'rating' => 4,
                'stock' => 90,
                'image_url' => 'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=900&q=80&headphones',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'electronics',
                'title' => 'Sony WH-1000XM5',
                'slug' => 'sony-wh-1000xm5',
                'description' => 'Industry leading noise cancellation.',
                'price' => 29990,
                'discount_percent' => 10,
                'rating' => 5,
                'stock' => 6,
                'image_url' => 'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=900&q=80&sony-headphones',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'electronics',
                'title' => 'Canon EOS R6 Mark II',
                'slug' => 'canon-eos-r6-mark-ii',
                'description' => 'Professional mirrorless.',
                'price' => 240000,
                'discount_percent' => 5,
                'rating' => 5,
                'stock' => 92,
                'image_url' => 'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=900&q=80&camera',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'electronics',
                'title' => 'iPad Air M2',
                'slug' => 'ipad-air-m2',
                'description' => 'Powerful tablet performance.',
                'price' => 59900,
                'discount_percent' => 12,
                'rating' => 5,
                'stock' => 63,
                'image_url' => 'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=900&q=80&ipad',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'electronics',
                'title' => 'Samsung Galaxy Tab S9',
                'slug' => 'samsung-galaxy-tab-s9',
                'description' => 'Best Android tablet.',
                'price' => 72000,
                'discount_percent' => 10,
                'rating' => 5,
                'stock' => 32,
                'image_url' => 'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=900&q=80&samsung-tablet',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'electronics',
                'title' => 'Kindle Paperwhite',
                'slug' => 'kindle-paperwhite',
                'description' => 'E-ink reading perfection.',
                'price' => 13999,
                'discount_percent' => 15,
                'rating' => 5,
                'stock' => 53,
                'image_url' => 'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=900&q=80&kindle',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'electronics',
                'title' => 'Sony Bravia 55" 4K TV',
                'slug' => 'sony-bravia-55-4k-tv',
                'description' => 'Vibrant cinema experience.',
                'price' => 85000,
                'discount_percent' => 18,
                'rating' => 5,
                'stock' => 9,
                'image_url' => 'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=900&q=80&tv',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'electronics',
                'title' => 'JBL Flip 6 Speaker',
                'slug' => 'jbl-flip-6-speaker',
                'description' => 'Portable waterproof sound.',
                'price' => 9999,
                'discount_percent' => 25,
                'rating' => 4,
                'stock' => 97,
                'image_url' => 'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=900&q=80&speaker',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'electronics',
                'title' => 'Logitech MX Master 3S',
                'slug' => 'logitech-mx-master-3s',
                'description' => 'Ultimate productivity mouse.',
                'price' => 10500,
                'discount_percent' => 10,
                'rating' => 5,
                'stock' => 76,
                'image_url' => 'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=900&q=80&mouse',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'electronics',
                'title' => 'Apple Watch Series 9',
                'slug' => 'apple-watch-series-9',
                'description' => 'Advanced health tracking.',
                'price' => 41900,
                'discount_percent' => 8,
                'rating' => 5,
                'stock' => 25,
                'image_url' => 'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=900&q=80&apple-watch',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'electronics',
                'title' => 'Samsung Galaxy Watch 6',
                'slug' => 'samsung-galaxy-watch-6',
                'description' => 'Classic smartwatch style.',
                'price' => 29999,
                'discount_percent' => 15,
                'rating' => 5,
                'stock' => 8,
                'image_url' => 'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=900&q=80&samsung-watch',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'electronics',
                'title' => 'GoPro Hero 12',
                'slug' => 'gopro-hero-12',
                'description' => 'Action ready video.',
                'price' => 45000,
                'discount_percent' => 12,
                'rating' => 5,
                'stock' => 24,
                'image_url' => 'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=900&q=80&gopro',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'electronics',
                'title' => 'DJI Mini 4 Pro Drone',
                'slug' => 'dji-mini-4-pro-drone',
                'description' => 'High-res aerial shots.',
                'price' => 95000,
                'discount_percent' => 5,
                'rating' => 5,
                'stock' => 63,
                'image_url' => 'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=900&q=80&drone',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'electronics',
                'title' => 'Seagate 2TB HDD',
                'slug' => 'seagate-2tb-hdd',
                'description' => 'Backup all your data.',
                'price' => 5800,
                'discount_percent' => 20,
                'rating' => 4,
                'stock' => 9,
                'image_url' => 'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=900&q=80&hard-drive',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'electronics',
                'title' => 'SanDisk 128GB Flash',
                'slug' => 'sandisk-128gb-flash',
                'description' => 'Fast file transfer.',
                'price' => 1200,
                'discount_percent' => 30,
                'rating' => 4,
                'stock' => 73,
                'image_url' => 'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=900&q=80&usb',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'electronics',
                'title' => 'TP-Link WiFi 6 Router',
                'slug' => 'tp-link-wifi-6-router',
                'description' => 'High speed home network.',
                'price' => 6500,
                'discount_percent' => 15,
                'rating' => 4,
                'stock' => 30,
                'image_url' => 'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=900&q=80&router',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'electronics',
                'title' => 'Belkin Wireless Charger',
                'slug' => 'belkin-wireless-charger',
                'description' => 'Fast Qi charging pad.',
                'price' => 2999,
                'discount_percent' => 20,
                'rating' => 4,
                'stock' => 94,
                'image_url' => 'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=900&q=80&wireless-charger',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'electronics',
                'title' => 'Anker 20000mAh Powerbank',
                'slug' => 'anker-20000mah-powerbank',
                'description' => 'Reliable travel power.',
                'price' => 3800,
                'discount_percent' => 25,
                'rating' => 4,
                'stock' => 17,
                'image_url' => 'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=900&q=80&powerbank',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'electronics',
                'title' => 'Corsair Mechanical Keyboard',
                'slug' => 'corsair-mechanical-keyboard',
                'description' => 'RGB gaming switch.',
                'price' => 12500,
                'discount_percent' => 10,
                'rating' => 5,
                'stock' => 100,
                'image_url' => 'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=900&q=80&keyboard',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'electronics',
                'title' => 'SteelSeries Gaming Mouse',
                'slug' => 'steelseries-gaming-mouse',
                'description' => 'Precision sensor tracking.',
                'price' => 5400,
                'discount_percent' => 15,
                'rating' => 4,
                'stock' => 52,
                'image_url' => 'https://images.unsplash.com/photo-1498049794561-7780e7231661?auto=format&fit=crop&w=900&q=80&gaming-mouse',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'home',
                'title' => 'Modern Table Lamp',
                'slug' => 'modern-table-lamp',
                'description' => 'Warm LED lighting.',
                'price' => 2499,
                'discount_percent' => 30,
                'rating' => 4,
                'stock' => 12,
                'image_url' => 'https://images.unsplash.com/photo-1484101403633-562f891dc89a?auto=format&fit=crop&w=900&q=80&lamp',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'home',
                'title' => 'Ergonomic Office Chair',
                'slug' => 'ergonomic-office-chair',
                'description' => 'High-back mesh support.',
                'price' => 14500,
                'discount_percent' => 45,
                'rating' => 5,
                'stock' => 78,
                'image_url' => 'https://images.unsplash.com/photo-1484101403633-562f891dc89a?auto=format&fit=crop&w=900&q=80&office-chair',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'home',
                'title' => 'Soft Velvet Cushion Set',
                'slug' => 'soft-velvet-cushion-set',
                'description' => 'Set of 5 luxury cushions.',
                'price' => 1499,
                'discount_percent' => 40,
                'rating' => 4,
                'stock' => 76,
                'image_url' => 'https://images.unsplash.com/photo-1484101403633-562f891dc89a?auto=format&fit=crop&w=900&q=80&cushions',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'home',
                'title' => 'Floating Wall Shelves',
                'slug' => 'floating-wall-shelves',
                'description' => 'Minimalist decor storage.',
                'price' => 1899,
                'discount_percent' => 25,
                'rating' => 4,
                'stock' => 92,
                'image_url' => 'https://images.unsplash.com/photo-1484101403633-562f891dc89a?auto=format&fit=crop&w=900&q=80&wall-shelf',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'home',
                'title' => 'Blackout Window Curtains',
                'slug' => 'blackout-window-curtains',
                'description' => 'Complete privacy curtains.',
                'price' => 2200,
                'discount_percent' => 30,
                'rating' => 4,
                'stock' => 90,
                'image_url' => 'https://images.unsplash.com/photo-1484101403633-562f891dc89a?auto=format&fit=crop&w=900&q=80&curtains',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'home',
                'title' => 'Shaggy Area Rug',
                'slug' => 'shaggy-area-rug',
                'description' => 'Soft and cozy rug.',
                'price' => 4500,
                'discount_percent' => 20,
                'rating' => 4,
                'stock' => 20,
                'image_url' => 'https://images.unsplash.com/photo-1484101403633-562f891dc89a?auto=format&fit=crop&w=900&q=80&rug',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'home',
                'title' => 'Memory Foam Mattress',
                'slug' => 'memory-foam-mattress',
                'description' => 'Better sleep tech.',
                'price' => 25000,
                'discount_percent' => 35,
                'rating' => 5,
                'stock' => 54,
                'image_url' => 'https://images.unsplash.com/photo-1484101403633-562f891dc89a?auto=format&fit=crop&w=900&q=80&mattress',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'home',
                'title' => 'Ceramic Flower Vase',
                'slug' => 'ceramic-flower-vase',
                'description' => 'Handcrafted pottery.',
                'price' => 899,
                'discount_percent' => 50,
                'rating' => 4,
                'stock' => 72,
                'image_url' => 'https://images.unsplash.com/photo-1484101403633-562f891dc89a?auto=format&fit=crop&w=900&q=80&vase',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'home',
                'title' => 'Nesting Coffee Tables',
                'slug' => 'nesting-coffee-tables',
                'description' => 'Smart space saving design.',
                'price' => 7800,
                'discount_percent' => 15,
                'rating' => 4,
                'stock' => 32,
                'image_url' => 'https://images.unsplash.com/photo-1484101403633-562f891dc89a?auto=format&fit=crop&w=900&q=80&coffee-table',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'home',
                'title' => 'Bamboo Shoe Rack',
                'slug' => 'bamboo-shoe-rack',
                'description' => 'Eco-friendly organizer.',
                'price' => 1200,
                'discount_percent' => 30,
                'rating' => 4,
                'stock' => 44,
                'image_url' => 'https://images.unsplash.com/photo-1484101403633-562f891dc89a?auto=format&fit=crop&w=900&q=80&shoe-rack',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'home',
                'title' => 'Cotton Bed Sheet Set',
                'slug' => 'cotton-bed-sheet-set',
                'description' => 'Breathable 400TC cotton.',
                'price' => 1800,
                'discount_percent' => 25,
                'rating' => 4,
                'stock' => 63,
                'image_url' => 'https://images.unsplash.com/photo-1484101403633-562f891dc89a?auto=format&fit=crop&w=900&q=80&bed-sheet',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'home',
                'title' => 'Indoor Large Plant',
                'slug' => 'indoor-large-plant',
                'description' => 'Natural air purifier.',
                'price' => 2400,
                'discount_percent' => 15,
                'rating' => 4,
                'stock' => 95,
                'image_url' => 'https://images.unsplash.com/photo-1484101403633-562f891dc89a?auto=format&fit=crop&w=900&q=80&plant',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'home',
                'title' => 'Wall Clock Minimalist',
                'slug' => 'wall-clock-minimalist',
                'description' => 'Silent sweep movement.',
                'price' => 1100,
                'discount_percent' => 40,
                'rating' => 4,
                'stock' => 69,
                'image_url' => 'https://images.unsplash.com/photo-1484101403633-562f891dc89a?auto=format&fit=crop&w=900&q=80&wall-clock',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'home',
                'title' => 'Scented Candle Pack',
                'slug' => 'scented-candle-pack',
                'description' => 'Aromatherapy relax set.',
                'price' => 650,
                'discount_percent' => 50,
                'rating' => 4,
                'stock' => 52,
                'image_url' => 'https://images.unsplash.com/photo-1484101403633-562f891dc89a?auto=format&fit=crop&w=900&q=80&candle',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'home',
                'title' => 'Door Mat Welcome',
                'slug' => 'door-mat-welcome',
                'description' => 'Non-slip outdoor mat.',
                'price' => 450,
                'discount_percent' => 60,
                'rating' => 4,
                'stock' => 78,
                'image_url' => 'https://images.unsplash.com/photo-1484101403633-562f891dc89a?auto=format&fit=crop&w=900&q=80&doormat',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'home',
                'title' => 'Kitchen Organizer Rack',
                'slug' => 'kitchen-organizer-rack',
                'description' => 'Stainless steel saver.',
                'price' => 1600,
                'discount_percent' => 25,
                'rating' => 4,
                'stock' => 26,
                'image_url' => 'https://images.unsplash.com/photo-1484101403633-562f891dc89a?auto=format&fit=crop&w=900&q=80&kitchen-rack',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'home',
                'title' => 'Mirror Gold Frame',
                'slug' => 'mirror-gold-frame',
                'description' => 'Vintage wall decoration.',
                'price' => 3500,
                'discount_percent' => 20,
                'rating' => 4,
                'stock' => 83,
                'image_url' => 'https://images.unsplash.com/photo-1484101403633-562f891dc89a?auto=format&fit=crop&w=900&q=80&mirror',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'home',
                'title' => 'Photo Frame Collage',
                'slug' => 'photo-frame-collage',
                'description' => 'Display your memories.',
                'price' => 1200,
                'discount_percent' => 30,
                'rating' => 4,
                'stock' => 32,
                'image_url' => 'https://images.unsplash.com/photo-1484101403633-562f891dc89a?auto=format&fit=crop&w=900&q=80&photo-frame',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'home',
                'title' => 'Throw Blanket Fleece',
                'slug' => 'throw-blanket-fleece',
                'description' => 'Extra warm sofa throw.',
                'price' => 1400,
                'discount_percent' => 35,
                'rating' => 4,
                'stock' => 52,
                'image_url' => 'https://images.unsplash.com/photo-1484101403633-562f891dc89a?auto=format&fit=crop&w=900&q=80&blanket',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'home',
                'title' => 'Storage Box Fabric',
                'slug' => 'storage-box-fabric',
                'description' => 'Organize your closet.',
                'price' => 850,
                'discount_percent' => 40,
                'rating' => 4,
                'stock' => 73,
                'image_url' => 'https://images.unsplash.com/photo-1484101403633-562f891dc89a?auto=format&fit=crop&w=900&q=80&storage-box',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'appliances',
                'title' => 'Air Fryer 5L',
                'slug' => 'air-fryer-5l',
                'description' => 'Oil-free preset cooking.',
                'price' => 6999,
                'discount_percent' => 25,
                'rating' => 5,
                'stock' => 61,
                'image_url' => 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=900&q=80&air-fryer',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'appliances',
                'title' => 'Robot Vacuum Cleaner',
                'slug' => 'robot-vacuum-cleaner',
                'description' => 'Smart mopping sweep.',
                'price' => 24999,
                'discount_percent' => 20,
                'rating' => 4,
                'stock' => 50,
                'image_url' => 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=900&q=80&robot-vacuum',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'appliances',
                'title' => 'Microwave Oven 20L',
                'slug' => 'microwave-oven-20l',
                'description' => 'Fast heating and grill.',
                'price' => 7500,
                'discount_percent' => 15,
                'rating' => 4,
                'stock' => 73,
                'image_url' => 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=900&q=80&microwave',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'appliances',
                'title' => 'Front Load Washing Machine',
                'slug' => 'front-load-washing-machine',
                'description' => 'Deep clean energy saver.',
                'price' => 32000,
                'discount_percent' => 10,
                'rating' => 5,
                'stock' => 47,
                'image_url' => 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=900&q=80&washing-machine',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'appliances',
                'title' => 'Double Door Fridge',
                'slug' => 'double-door-fridge',
                'description' => 'Inverter cooling tech.',
                'price' => 28500,
                'discount_percent' => 12,
                'rating' => 5,
                'stock' => 17,
                'image_url' => 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=900&q=80&refrigerator',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'appliances',
                'title' => 'Dishwasher 12 Place',
                'slug' => 'dishwasher-12-place',
                'description' => 'Water efficient cleaning.',
                'price' => 45000,
                'discount_percent' => 8,
                'rating' => 4,
                'stock' => 8,
                'image_url' => 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=900&q=80&dishwasher',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'appliances',
                'title' => 'Water Purifier RO+UV',
                'slug' => 'water-purifier-ro-uv',
                'description' => 'Safe drinking water tech.',
                'price' => 12500,
                'discount_percent' => 20,
                'rating' => 5,
                'stock' => 33,
                'image_url' => 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=900&q=80&water-purifier',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'appliances',
                'title' => 'Tower Air Cooler',
                'slug' => 'tower-air-cooler',
                'description' => 'Smart cooling for summer.',
                'price' => 8900,
                'discount_percent' => 15,
                'rating' => 4,
                'stock' => 95,
                'image_url' => 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=900&q=80&air-cooler',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'appliances',
                'title' => 'Electric Kettle 1.5L',
                'slug' => 'electric-kettle-1-5l',
                'description' => 'Fast boiling safety.',
                'price' => 1200,
                'discount_percent' => 30,
                'rating' => 4,
                'stock' => 15,
                'image_url' => 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=900&q=80&kettle',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'appliances',
                'title' => 'Juicer Mixer Grinder',
                'slug' => 'juicer-mixer-grinder',
                'description' => 'Powerful blade crushing.',
                'price' => 4800,
                'discount_percent' => 25,
                'rating' => 4,
                'stock' => 24,
                'image_url' => 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=900&q=80&mixer',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'appliances',
                'title' => 'Steam Iron',
                'slug' => 'steam-iron',
                'description' => 'Wrinkle free clothing.',
                'price' => 2400,
                'discount_percent' => 35,
                'rating' => 4,
                'stock' => 43,
                'image_url' => 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=900&q=80&iron',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'appliances',
                'title' => 'Vacuum Cleaner Stick',
                'slug' => 'vacuum-cleaner-stick',
                'description' => 'Cordless lightweight reach.',
                'price' => 15500,
                'discount_percent' => 15,
                'rating' => 4,
                'stock' => 22,
                'image_url' => 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=900&q=80&stick-vacuum',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'appliances',
                'title' => 'Induction Cooktop',
                'slug' => 'induction-cooktop',
                'description' => 'Safe and fast cooking.',
                'price' => 3200,
                'discount_percent' => 20,
                'rating' => 4,
                'stock' => 47,
                'image_url' => 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=900&q=80&induction',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'appliances',
                'title' => 'Bread Toaster 2 Slice',
                'slug' => 'bread-toaster-2-slice',
                'description' => 'Crispy breakfast toast.',
                'price' => 1400,
                'discount_percent' => 40,
                'rating' => 4,
                'stock' => 12,
                'image_url' => 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=900&q=80&toaster',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'appliances',
                'title' => 'Coffee Maker Espresso',
                'slug' => 'coffee-maker-espresso',
                'description' => 'Barista style at home.',
                'price' => 18500,
                'discount_percent' => 10,
                'rating' => 5,
                'stock' => 52,
                'image_url' => 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=900&q=80&coffee-maker',
                'is_featured' => false,
            ],
            [
                'category_slug' => 'appliances',
                'title' => 'OTG Oven 30L',
                'slug' => 'otg-oven-30l',
                'description' => 'Baking and roasting pro.',
                'price' => 6500,
                'discount_percent' => 15,
                'rating' => 4,
                'stock' => 69,
                'image_url' => 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=900&q=80&otg',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'appliances',
                'title' => 'Ceiling Fan Smart',
                'slug' => 'ceiling-fan-smart',
                'description' => 'Remote and app control.',
                'price' => 4200,
                'discount_percent' => 25,
                'rating' => 4,
                'stock' => 79,
                'image_url' => 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=900&q=80&fan',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'appliances',
                'title' => 'Hand Blender',
                'slug' => 'hand-blender',
                'description' => 'Multi-purpose blending.',
                'price' => 1500,
                'discount_percent' => 30,
                'rating' => 4,
                'stock' => 44,
                'image_url' => 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=900&q=80&blender',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'appliances',
                'title' => 'Sandwich Maker',
                'slug' => 'sandwich-maker',
                'description' => 'Quick and easy snacks.',
                'price' => 1800,
                'discount_percent' => 35,
                'rating' => 4,
                'stock' => 74,
                'image_url' => 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=900&q=80&sandwich-maker',
                'is_featured' => true,
            ],
            [
                'category_slug' => 'appliances',
                'title' => 'Hair Dryer Professional',
                'slug' => 'hair-dryer-professional',
                'description' => 'Fast salon style dry.',
                'price' => 2200,
                'discount_percent' => 25,
                'rating' => 4,
                'stock' => 51,
                'image_url' => 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=900&q=80&hair-dryer',
                'is_featured' => false,
            ],
        ];

        foreach ($products as $product) {
            $category = Category::query()->where('slug', $product['category_slug'])->first();
            if (!$category) continue;
            unset($product['category_slug']);
            $product['category_id'] = $category->id;
            Product::query()->updateOrCreate(['slug' => $product['slug']], $product);
        }
    }
}
